### ISSUE TITLE
Hangs Octoprint while communication with HA is not viable

### ISSUE THREAD

**Issue by tiagofreire-pt** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#11]
The printing job gets sluggish (1 instruction per 5 seconds) and gives the error bellow, while the plugin can't communicate with the HA instance (reboot, e.g.) or when the switch entity changed its name or reference on HA.

"Communication timeout while printing"

More info at: https://community.octoprint.org/t/bug-communication-timeout-while-printing/26483/14

**Comment by edekeijzer** [comment]
You probably have the "Automatically turn PSU on" option enabled inPSUControl. This will try to send a command to HA for each of the Gcodes in the list. When it's not available the plugin will block until time-out.
Disable the option or leave only the codes used at startup (preheat, leveling) to prevent this from happening.

**Comment by tiagofreire-pt** [comment]
Yes, I have the "Automatically turn PSU on" turned on.

This is a bug, because if the HA reboots or the network goes down while printing, the print gets trashed just because this plugin does not resolve softly the connectivity issue, bugging the printer to the point of being useless.

**Comment by wieluk** [comment]
Yea same happend for me. Home assistant crashed and the printerhead moved really laggy and paused after every move. Maybe we should just send nothing if the switch state is unavailable?

**Comment by ark-** [comment]
Yep, ruined 3 prints for me. Took restarting in safe mode to confirm it was a plugin, then going through every plugin's issue pages to find this.

The call to HA should be asynchronous from the printing. Why wait if nothing happens from a failed response? 

I will just remove this plugin altogether for now and manually control my printer's smart plug from HA app. I'm now concerned any of the other settings could cause similar issues.

**Comment by edekeijzer** [comment]
> Yes, I have the "Automatically turn PSU on" turned on.
> 
> This is a bug, because if the HA reboots or the network goes down while printing, the print gets trashed just because this plugin does not resolve softly the connectivity issue, bugging the printer to the point of being useless.

It is a known issue, but not a bug as I see it. This plugin is nothing more than a few functions for PSUControl execute instead of its own built-in functions to turn the PSU on/off or check its state. You explicitly request to switch the PSU on at each Gcode command. If HA is not available, it is not possible to fulfill this request, so the function will return failure.

There is a simple workaround, disable the "Automatically turn PSU on" option. Please explain to me why this is not a viable option, as I fail to see the use of constantly firing incredible amounts of API commands to Home Assistant.
