### ISSUE TITLE
Plugin calls Home Assistant every second

### ISSUE THREAD

**Issue by TwoPlayer** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#14]
Hey,
I have a pihole in my network, so I noticed, that the Plugin is calling Home Assistant every second. Is there a possiblity to limit this or is something not working with my Home Assistant/Octopi Installation?

These are the network calls:
![grafik](https://user-images.githubusercontent.com/2150354/177810471-76d62d87-4321-4acc-8b66-80dd017af337.png)

The red is octopi:
![grafik](https://user-images.githubusercontent.com/2150354/177810612-a503215f-06b2-44e9-8f7f-9af67f779e2e.png)

Best regards,
Simon

**Comment by edekeijzer** [comment]
If it is every second, you probably have modified the polling interval in the main PSUControl plugin, which should be every 5 seconds.
This is due to the way PSUControl was once designed. As long as it's polling internally (checking serial connection with the printer or a GPIO pin on a Raspberry Pi) nobody will see. Now that the status is being polled over the network, something like PiHole will indeed visualise the amount of calls being done. For each poll a new connection is created and it seems that the Python requests library will do a DNS query for a new connection. I will try if creating a session in requests and re-using that session will reduce the amount of DNS queries.

**Comment by TwoPlayer** [comment]
Hello, thank you for the respond. I had indeed modified the polling interval in the main PSUControl plugin, because I had another PSU Add-On Plugin before and forget to change it again. If creating a session in requests and re-using that session will help reduce the DNS queries, it would be really nice. Thank you for looking in to it.

**Comment by edekeijzer** [comment]
So I quickly set up a PiHole server and implemented the possible fix in my test environment but unfortunately it didn't make any difference. It's the behaviour of the requests library (which is _the_ Python library for HTTP requests) so I'm afraid there's not much I can do.
A workaround could be to install a DNS cache on the Octoprint host.
